### PR TITLE
add increasingly slow loop example

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by carstenbauer** [comment]
This is a mapreduce with `f=fib`. I would use a local summation for each task and only write to the outer array once at the end. See the mapreduce folder.

**Comment by carstenbauer** [comment]
Btw, we also need a nested example and Fibonacci could be a candidate for this. (But we can also take something basic)

**Comment by Moelf** [comment]
How about I convert this to nested example, at which level do we parallel?

**Comment by carstenbauer** [comment]
Hm, maybe Fibonacci isn't the best example after all. What we want is likely the following: a simple parallel program that we then run as part of a parallel reduction. I.e. a parallel `mapreduce(f, +, ...)` where `f` is also parallelised (and produces uniform workload). However, to be able to use and compare `@threads`, we need a for-loop kind of parallelization and this is probably non-trivial for Fibonacci (although potentially [doable](https://codereview.stackexchange.com/questions/163354/using-2-threads-to-compute-the-nth-fibonacci-number-with-memoization)). I think we should just choose any simple and convenient parallel algorithm.

(Maybe a basic parallel matmul could be a choice for `f`? Or the standard [parallel pi computation](https://github.com/carstenbauer/JuliaHLRS23/tree/main/exercises/Day3/1_montecarlo_pi)? I'm not very creative right now 😄)

**Pull request closed without merging**
